### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ktun95** [dictybase-playground/lexical-table-demo#1]
- [x] Add github actions (create PR, linting at least) 
- [ ] Add precommit yaml
- [x] Add error boundary to Rich Text Plugin
- [x] Implement exportJSON and importJSON in CustomTableNode
- [ ] adjust table width calculation
- [x] finish refactoring custom table plugin
- [x] refactor createCustomTableWithDimensions to remove for loops
- [ ] testing for custom table node
- [x] revisit methods for custom table nodes
- [ ] add image plugin
